import g1 from '../../../assets/images/mainShop/generalBMX/g1.jpg';

export const mainShopProducts = {
  generalBMX: {
    products: [
      {
        image: g1,
        name: 'ga1',
        price: 3020,
        popularity: 12,
      },
      {
        image: g1,
        name: 'ga2',
        price: 3100,
        popularity: 43123,
      },
      {
        image: g1,
        name: 'g3',
        price: 30,
        popularity: 13,
      },
      {
        image: g1,
        name: 'ah',
        price: 1300,
        popularity: 34,
      },
      {
        image: g1,
        name: 'h5',
        price: 3,
        popularity: 56,
      },
      {
        image: g1,
        name: 'g7',
        price: 4300,
        popularity: 70,
      },
      {
        image: g1,
        name: 'j8',
        price: 11300,
        popularity: 80,
      },
      {
        image: g1,
        name: 'sd2',
        price: 30230,
        popularity: 89,
      },
      {
        image: g1,
        name: 'a23',
        price: 320,
        popularity: 99,
      },
      {
        image: g1,
        name: 'h77',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'd2312',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: '22s',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'sdf4',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'fb3',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'fga',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'nui',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'sd211',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: '123d',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'ccb23',
        price: 352,
        popularity: 100,
      },
    ],
  },
  RNDMBMX: {
    products: [
      {
        image: g1,
        name: 'r121',
        price: 3020,
        popularity: 12,
      },
      {
        image: g1,
        name: 'r5',
        price: 3100,
        popularity: 43123,
      },
      {
        image: g1,
        name: 'r44',
        price: 30,
        popularity: 13,
      },
      {
        image: g1,
        name: 'r123',
        price: 1300,
        popularity: 34,
      },
      {
        image: g1,
        name: 'r44',
        price: 3,
        popularity: 56,
      },
      {
        image: g1,
        name: 'r7',
        price: 4300,
        popularity: 70,
      },
      {
        image: g1,
        name: 'r123',
        price: 11300,
        popularity: 80,
      },
      {
        image: g1,
        name: 'rb',
        price: 30230,
        popularity: 89,
      },
      {
        image: g1,
        name: 'r677',
        price: 320,
        popularity: 99,
      },
      {
        image: g1,
        name: 'rv',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'r678',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'rqa',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'rasc',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'rrr',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'r111',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'r234',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'ra1',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'rrs',
        price: 352,
        popularity: 100,
      },
      {
        image: g1,
        name: 'rq',
        price: 352,
        popularity: 100,
      },
    ],
  },
  UniqueBMX: {
    products: [],
  },
  ExoticBMX: {
    products: [],
  },
};
